# Generated by Django 4.0.4 on 2022-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Client', models.DecimalField(decimal_places=0, max_digits=10)),
                ('UserName', models.CharField(max_length=20)),
                ('MotdePasse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Service', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Id_Client', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Service', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Web_adresse_Img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Service', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Nom_Service', models.TextField()),
                ('Type_Service', models.CharField(max_length=50)),
                ('Longitude_Service', models.CharField(max_length=50)),
                ('Latitude_Service', models.CharField(max_length=50)),
                ('Score', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
