# Generated by Django 4.0.4 on 2022-06-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_delete_client_delete_commentaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='index.image')),
                ('serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='index.service')),
            ],
        ),
    ]
