# Generated by Django 4.0.4 on 2022-06-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_commentaire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaire',
            new_name='Favoris',
        ),
    ]
