# Generated by Django 4.0.4 on 2022-06-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_rename_commentaire_favoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoris',
            name='img',
        ),
    ]
