# Generated by Django 4.0.4 on 2022-06-19 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0007_remove_favoris_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favoris',
        ),
    ]
