# Generated by Django 4.0.4 on 2022-06-30 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0008_service_fav_delete_favoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='fav',
        ),
        migrations.AddField(
            model_name='service',
            name='users_wishlist',
            field=models.ManyToManyField(related_name='us', to=settings.AUTH_USER_MODEL),
        ),
    ]
