# Generated by Django 4.0.4 on 2022-06-30 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0010_remove_service_users_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='users_wishlist',
            field=models.ManyToManyField(related_name='us', to=settings.AUTH_USER_MODEL),
        ),
    ]
